name: Aurh

on:
  push:
    branches:
     - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Golang
      uses: actions/setup-go@v5
      with:
       go-version: '1.22.2'

      - name: Install Deb
      run: go mod download


      - name: Build
        run: go build -v ./...

      - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }
        port: ${{ secrets.PORT }
        script: |
          cd Desktop/go/src/github.com/Imtihon3/Auth-Service
          git pull
          sudo docker compose down
          sudo docker compose up -d
