name: Auth

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Download Go Dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e  # Exit on any error
            cd car-person/Car-Auth-Service/
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d

            cd ../Car-Api-Gateway/
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d

            cd ../Car-Booking-Service/
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d
